### ISSUE TITLE
Use correct url for bootstrap.pypa.io

### ISSUE THREAD

**Issue by ozin7** [lemberg/draft-environment#241]
Correct URL: https://bootstrap.pypa.io/pip/3.5/get-pip.py

**Comment by T2L** [comment]
Please see #234

What version do you use?

**Comment by ozin7** [comment]
Ahh, ok

**Comment by ozin7** [comment]
@T2L 
I was sure I saw `https://bootstrap.pypa.io/pip/3.5/get-pip.py` url in https://github.com/lemberg/draft-environment/blob/3.x.x/Vagrantfile#L234 but it is not.
On https://bootstrap.pypa.io/3.5/get-pip.py it says that we should use `https://bootstrap.pypa.io/pip/3.5/get-pip.py`.

Do you think it should be fixed, if so give me access and I will create a MR😝

**Comment by T2L** [comment]
Yup, seems like this is a new issue due to a change in the pip itself. However, a simple redirect would work as well 🤔 

See https://github.com/pypa/get-pip/commit/2360f025eb2a6f62d45cf99e4c6d83ba9c4d5e37
