### ISSUE TITLE
Files access permissions.

### ISSUE THREAD

**Issue by iVegas** [lemberg/draft-environment#54]
**User story:**

> As an authorized Drupal user,  I want to upload a file for my profile photo.
> I go to the user edit form, choose the file for photo field and see the error "The file could not be uploaded."

**Current workaround:**
Set `777` permission for `sites/default/files` directory on the host machine.
`775` permission does no any effect on the file accessibility.

Looks like server user doesn't related to the user's group with permission to manage files.

Reproduced on `lemberg/draft-environment:2.0.2`
Host machine `Ubuntu 17.10`
Virtualbox `5.2.0`
Vagrant `2.0.1`

**Comment by T2L** [comment]
I believe this is not relevant anymore
